name=TinyLink
version=1.0.0
author=Pete Sramek
maintainer=Pete Sramek
sentence=A lightweight, template-based serial protocol for reliable UART communication.
paragraph=Features a robust state machine and checksum validation for data integrity. Hardware-agnostic and optimized for resource-constrained devices like the MH-Tiny88 and ESP-M3.
category=Communication
url=https://github.com/petesramek/tiny-link/
architectures=*
includes=TinyLink.h
